#!/bin/sh

set -e

DAEMON=/usr/sbin/cron
PIDFILE=/var/run/crond.pid

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Define LSB log_* functions.
. /lib/lsb/init-functions

do_start()
{
        # Return
        #   0 if daemon has been started
        #   1 if daemon was already running
        #   other if daemon could not be started or a failure occured
        start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON
}

do_stop()
{
        # Return
        #   0 if daemon has been stopped
        #   1 if daemon was already stopped
        #   other if daemon could not be stopped or a failure occurred
        start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --exec $DAEMON
}

case "$1" in
    start) do_start
	case "$?" in
                0) sendsigs_omit
                   log_end_msg 0 ;;
                1) log_progress_msg "already started"
                   log_end_msg 0 ;;
                *) log_end_msg 1 ;;
        esac
	;;
    stop) do_stop
	case "$?" in
            0) log_end_msg 0 ;;
            1) log_progress_msg "already stopped"
                log_end_msg 0 ;;
            *) log_end_msg 1 ;;
        esac
	;;
    *)
	;;
esac
	
